spring:
  application:
    name: bootcamp-user
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

server:
  port: 8081
  servlet:
    context-path: /bootcamp/user

aws:
  region: us-east-1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationSorter: alpha
  version: 1.0.0

debug: true
