package com.example.bootcamp.user.ports.driven.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

@DynamoDBTable(tableName = "profile")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ProfileEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "user_id")
    private Long userId;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "developer_rol")
    private String developerRol;

    @DynamoDBAttribute(attributeName = "badges")
    private List<String> badges;

    @DynamoDBAttribute(attributeName = "social_media")
    private Map<String, String> socialMedia;

    @DynamoDBAttribute(attributeName = "hobbies")
    private List<String> hobbies;

    @DynamoDBAttribute(attributeName = "staff_rol")
    private String staffRol;
}
